Script "LexiconActorSpawner" (void)
{
	int mapsetPrefix = strleft(strparam(n:PRINTNAME_LEVEL), 4);
	str spawnerId = strparam(d:GetUserVariable(0, "user_id"));
	str spawnerActor = getDynLangEntry(mapsetPrefix, "ACTOR", spawnerId);
	//printbold(s:mapsetPrefix, s:"_ACTOR_", s:spawnerId, s:": ", s:spawnerActor);

	// check if this language definition exists
	if(mapsetPrefix != "_LANG_UNDEFINED_")
	{
		actorSpawn(spawnerActor);
	}
}
