bool keysFound[6];

str keyNames[6] =
{
	"RedCard",
	"YellowCard",
	"BlueCard",
	"RedSkull",
	"YellowSkull",
	"BlueSkull"
};

script "SharedKey_Pickup" (int key)
{
	if (keysFound[key] == FALSE)
	{
		if (GetCVar("sv_sharekeys") == 1 && GameType() == GAME_NET_COOPERATIVE)
		{
			GiveActorInventory(0, keyNames[key], 1);
		}
		else
		{
			GiveInventory(keyNames[key], 1);
		}

		keysFound[key] = TRUE;
		SetResultValue(0);
	}
	else
	{
		GiveInventory(keyNames[key], 1);
		SetResultValue(1);
	}
}