/*
	Lexicon Slaughtermap Expansion Pack
	Map Scripts
*/

#import "zcommon.bcs"
#library "LEXSLGT"

Script "Lexicon_SlaughterPack_AddAcronym" OPEN
{
	ACS_NamedExecuteWithResult("Lexicon_AddMapSet","SLGT",2);
}

script "LexiconSlaughterExpansionPackMapScripts" ENTER
{
	str mapName = StrParam(n:PRINTNAME_LEVEL);

	// NoReason's Speedmaps 2
	if (StrICmp(mapName,"NSP212") == 0)
	{
		if (ACS_NamedExecuteWithResult("LexiconIsGameModded") == 0)
		{
			ClearInventory();
			SetActorProperty(0, APROP_HEALTH, 100);
			GiveInventory("Fist", 1);
			GiveInventory("Pistol", 1); 
			GiveInventory("LexiconClipGive", 30);
			GiveInventory("LexiconInventoryGiven", 1);
			SetWeapon("Pistol");
		}
	}
	if (StrICmp(mapName,"NSP214") == 0)
	{
		if (ACS_NamedExecuteWithResult("LexiconIsGameModded") == 0)
		{
			ClearInventory();
			SetActorProperty(0, APROP_HEALTH, 100);
			GiveInventory("Fist", 1);
			GiveInventory("Pistol", 1); 
			GiveInventory("LexiconClipGive", 30);
			GiveInventory("LexiconInventoryGiven", 1);
			SetWeapon("Pistol");
		}
	}
	if (StrICmp(mapName,"NSP220") == 0)
	{
		if (ACS_NamedExecuteWithResult("LexiconIsGameModded") == 0)
		{
			ClearInventory();
			SetActorProperty(0, APROP_HEALTH, 100);
			GiveInventory("Fist", 1);
			GiveInventory("Pistol", 1); 
			GiveInventory("LexiconClipGive", 30);
			GiveInventory("LexiconInventoryGiven", 1);
			SetWeapon("Pistol");
		}
	}
	if (StrICmp(mapName,"NSP222") == 0)
	{
		if (ACS_NamedExecuteWithResult("LexiconIsGameModded") == 0)
		{
			ClearInventory();
			SetActorProperty(0, APROP_HEALTH, 100);
			GiveInventory("Fist", 1);
			GiveInventory("Pistol", 1); 
			GiveInventory("LexiconClipGive", 30);
			GiveInventory("LexiconInventoryGiven", 1);
			SetWeapon("Pistol");
		}
	}
}